=== MariaBrunet/SuperYacht/xml/reserves.dtd
<!ELEMENT reserves (reserva*)>
    <!ELEMENT reserva (idBarco, persona, data)>
    <!ATTLIST reserva id ID #REQUIRED>
        <!ELEMENT idBarco (#PCDATA)>
        <!ELEMENT persona (nom, llinatge1, llinatge2, dni, telf, direccio)>
            <!ELEMENT nom (#PCDATA)>
            <!ELEMENT llinatge1 (#PCDATA)>
            <!ELEMENT llinatge2 (#PCDATA)>
            <!ELEMENT dni (#PCDATA)>
            <!ELEMENT telf (#PCDATA)>
            <!ELEMENT direccio (#PCDATA)>
        <!ELEMENT data (entrada, sortida)>
            <!ELEMENT entrada (#PCDATA)>
            <!ELEMENT sortida (#PCDATA)>

=== MariaBrunet/SuperYacht/xml/reserves.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reserves SYSTEM "reserves.dtd">
<reserves>
    <reserva id="ID">
        <idBarco>1</idBarco>
        <persona>
            <nom>Maria</nom>
            <llinatge1>Brunet</llinatge1>
            <llinatge2>Vallcaneras</llinatge2>
            <dni>12345678</dni>
            <telf>660937882</telf>
            <direccio>c/ Manacor nÂº 25</direccio>
        </persona>
        <data>
            <entrada>07/13/2016</entrada>
            <sortida>21/13/2016</sortida>
        </data>
    </reserva>
<reserva><idBarco>1</idBarco><persona><nom>a</nom><llinatge1>b</llinatge1><llinatge2>c</llinatge2><dni>d</dni><telf>e</telf><direccio>f</direccio></persona><data><entrada>07/20/2016</entrada><sortida>07/28/2016</sortida></data></reserva><reserva><idBarco>1</idBarco><persona><nom>P</nom><llinatge1>asd</llinatge1><llinatge2>asd</llinatge2><dni>asd</dni><telf>sad</telf><direccio>sad</direccio></persona><data><entrada>07/11/2016</entrada><sortida>07/20/2016</sortida></data></reserva><reserva><idBarco>1</idBarco><persona><nom>asd</nom><llinatge1>sad</llinatge1><llinatge2>sad</llinatge2><dni>sad</dni><telf>sadsad</telf><direccio>sad</direccio></persona><data><entrada>07/06/2016</entrada><sortida>07/23/2016</sortida></data></reserva><reserva><idBarco>1</idBarco><persona><nom>asd</nom><llinatge1>asd</llinatge1><llinatge2>asd</llinatge2><dni>asd</dni><telf>asdasd</telf><direccio>asd</direccio></persona><data><entrada>07/06/2016</entrada><sortida>07/09/2016</sortida></data></reserva><reserva><idBarco>1</idBarco><persona><nom/><llinatge1/><llinatge2/><dni/><telf/><direccio/></persona><data><entrada>08/14/2016</entrada><sortida>08/20/2016</sortida></data></reserva><reserva><idBarco>1</idBarco><persona><nom/><llinatge1/><llinatge2/><dni/><telf/><direccio/></persona><data><entrada>07/07/2016</entrada><sortida>07/15/2016</sortida></data></reserva><reserva><idBarco/><persona><nom/><llinatge1/><llinatge2/><dni/><telf/><direccio/></persona><data><entrada>07/07/2016</entrada><sortida>07/22/2016</sortida></data></reserva><reserva><idBarco>Diamonds are forever</idBarco><persona><nom/><llinatge1/><llinatge2/><dni/><telf/><direccio/></persona><data><entrada>07/06/2016</entrada><sortida>07/30/2016</sortida></data></reserva><reserva><idBarco>Delfino 93'</idBarco><persona><nom/><llinatge1/><llinatge2/><dni/><telf/><direccio/></persona><data><entrada>07/07/2016</entrada><sortida>07/01/2016</sortida></data></reserva><reserva><idBarco>Delfino 93'</idBarco><persona><nom/><llinatge1/><llinatge2/><dni/><telf/><direccio/></persona><data><entrada>07/07/2016</entrada><sortida>07/01/2016</sortida></data></reserva><reserva><idBarco>Delfino 93'</idBarco><persona><nom/><llinatge1/><llinatge2/><dni/><telf/><direccio/></persona><data><entrada>07/07/2016</entrada><sortida>07/01/2016</sortida></data></reserva><reserva><idBarco>Delfino 93'</idBarco><persona><nom/><llinatge1/><llinatge2/><dni/><telf/><direccio/></persona><data><entrada>07/07/2016</entrada><sortida>07/01/2016</sortida></data></reserva><reserva><idBarco>Diamonds are forever</idBarco><persona><nom/><llinatge1/><llinatge2/><dni/><telf/><direccio/></persona><data><entrada>07/07/2016</entrada><sortida>07/02/2016</sortida></data></reserva><reserva><idBarco>Grande 100</idBarco><persona><nom>asdasdasd</nom><llinatge1/><llinatge2/><dni/><telf/><direccio/></persona><data><entrada>07/07/2016</entrada><sortida>07/09/2016</sortida></data></reserva></reserves>
